import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import EvmWalletProvider from "@/providers/EvmWalletProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <EvmWalletProvider>
          <main className="w-full no-scrollbar">
            <div className="min-h-screen flex flex-col bg-[#150A2A]">
              <header className="sticky top-0 z-50 ">
                <Navbar />
              </header>
              <main className="flex-grow overflow-hidden">{children}</main>
              <footer className="flex flex-col">
                <Footer />
              </footer>
            </div>
          </main>
        </EvmWalletProvider>
      </body>
    </html>
  );
}
